basePath: /
definitions:
  models.PaymentStatus:
    enum:
    - Authorized
    - Declined
    - Rejected
    type: string
    x-enum-varnames:
    - Authorized
    - Declined
    - Rejected
  models.PostPaymentRequest:
    properties:
      amount:
        type: integer
      card_number:
        type: string
      currency:
        type: string
      cvv:
        type: string
      expiry_month:
        type: integer
      expiry_year:
        type: integer
    type: object
  models.PostPaymentResponse:
    properties:
      amount:
        type: integer
      card_number_last_four:
        type: string
      currency:
        type: string
      expiry_month:
        type: integer
      expiry_year:
        type: integer
      id:
        type: string
      payment_status:
        $ref: '#/definitions/models.PaymentStatus'
    type: object
host: localhost:8090
info:
  contact: {}
  description: Interview challenge for building a Payment Gateway - Go version
  title: Payment Gateway Challenge Go
paths:
  /api/payments:
    post:
      consumes:
      - application/json
      description: Processes a card payment through the payment gateway
      parameters:
      - description: Payment request
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/models.PostPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostPaymentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.PostPaymentResponse'
        "502":
          description: Bad Gateway
          schema:
            type: string
      summary: Create a payment
      tags:
      - payments
  /api/payments/{id}:
    get:
      description: Retrieves a previously processed payment
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostPaymentResponse'
        "204":
          description: No Content
          schema:
            type: string
      summary: Get payment
      tags:
      - payments
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
